apiVersion: apps/v1
kind: Deployment
metadata:
  name: leave-management-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leave-app
  template:
    metadata:
      labels:
        app: leave-app
    spec:
      containers:
      - name: leave-app-container
        image: priyanappu30/leave-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
